import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased max-w-4xl mx-auto`}
    >
      <body className="min-h-full flex flex-col">
      <ThemeProvider
       attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
       <Header/>
        {children}
      </ThemeProvider>
     </body>
    </html>
  );
}
